--------------------------------------------------------
-- Archivo creado  - miércoles-agosto-31-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence FUNCIONALIDAD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FUNCIONALIDAD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 6 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PERSONA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PERSONA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence ROL_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ROL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table FUNCIONALIDAD
--------------------------------------------------------

  CREATE TABLE "FUNCIONALIDAD" 
   (	"ID_FUNCIONALIDAD" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"DESCRIPCION" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERSONA
--------------------------------------------------------

  CREATE TABLE "PERSONA" 
   (	"ID_PERSONA" NUMBER(*,0), 
	"DOCUMENTO" VARCHAR2(20 BYTE), 
	"APELLIDO1" VARCHAR2(20 BYTE), 
	"APELLIDO2" VARCHAR2(20 BYTE), 
	"NOMBRE1" VARCHAR2(20 BYTE), 
	"NOMBRE2" VARCHAR2(20 BYTE), 
	"MAIL" VARCHAR2(50 BYTE), 
	"CLAVE" VARCHAR2(20 BYTE), 
	"FEC_NAC" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROL
--------------------------------------------------------

  CREATE TABLE "ROL" 
   (	"ID_ROL" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"DESCRIPCION" VARCHAR2(255 BYTE), 
	"TIPO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROL_FUNCION
--------------------------------------------------------

  CREATE TABLE "ROL_FUNCION" 
   (	"ID_ROL_FUNCION" NUMBER(*,0), 
	"ID_ROL" NUMBER(*,0), 
	"ID_FUNCION" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into FUNCIONALIDAD
SET DEFINE OFF;
Insert into FUNCIONALIDAD (ID_FUNCIONALIDAD,NOMBRE,DESCRIPCION) values ('1','Control de inventario','Realizar una gestión de las existencias de un almacén.');
Insert into FUNCIONALIDAD (ID_FUNCIONALIDAD,NOMBRE,DESCRIPCION) values ('2','VentasVentas','Ventas son las actividades realizadas para incentivar potenciales clientes a realizar una determinada compra.');
Insert into FUNCIONALIDAD (ID_FUNCIONALIDAD,NOMBRE,DESCRIPCION) values ('3','Compras','La compra es la acción de obtener algo mediante el pago de una cantidad de dinero.');
Insert into FUNCIONALIDAD (ID_FUNCIONALIDAD,NOMBRE,DESCRIPCION) values ('4','Cuenta corriente','La cuenta corriente bancaria es un contrato entre una persona o empresa y un Banco, mediante la cual el primero deposita dinero.');
Insert into FUNCIONALIDAD (ID_FUNCIONALIDAD,NOMBRE,DESCRIPCION) values ('5','Sueldos','El salario o sueldo es la remuneración recibida por una persona como pago por su trabajo. De esta forma, el empleado puede beneficiarse de su contribución.');
REM INSERTING into PERSONA
SET DEFINE OFF;
Insert into PERSONA (ID_PERSONA,DOCUMENTO,APELLIDO1,APELLIDO2,NOMBRE1,NOMBRE2,MAIL,CLAVE,FEC_NAC) values ('0','52477954','RAMOS','GONZALEZ','JUAN','MANUEL','juan.ramos@gmail.com','123',null);
Insert into PERSONA (ID_PERSONA,DOCUMENTO,APELLIDO1,APELLIDO2,NOMBRE1,NOMBRE2,MAIL,CLAVE,FEC_NAC) values ('1','56787889','MARTINEZ','GONZALEZ','ALICIA','JUANA','alicia123@gmail.com','54879',null);
Insert into PERSONA (ID_PERSONA,DOCUMENTO,APELLIDO1,APELLIDO2,NOMBRE1,NOMBRE2,MAIL,CLAVE,FEC_NAC) values ('2','45657897','BALLESTERO','AGUILAR','JESUS','MIGUEL','jesus.ballestero@hotmail.com','hj4',null);
Insert into PERSONA (ID_PERSONA,DOCUMENTO,APELLIDO1,APELLIDO2,NOMBRE1,NOMBRE2,MAIL,CLAVE,FEC_NAC) values ('3','46577789','PALOMINO','MARTINEZ','MANUEL','ANTONIO','manu.palomino2@gmail.com','54gg',null);
Insert into PERSONA (ID_PERSONA,DOCUMENTO,APELLIDO1,APELLIDO2,NOMBRE1,NOMBRE2,MAIL,CLAVE,FEC_NAC) values ('4','34879845','CEBALLOS','PALMA','ROSA','MARIA','mariarosa@gmail.com','qwerty',null);
REM INSERTING into ROL
SET DEFINE OFF;
Insert into ROL (ID_ROL,NOMBRE,DESCRIPCION,TIPO) values ('1','CONTADOR','HACE CUENTAS','JEFE_SECCION');
Insert into ROL (ID_ROL,NOMBRE,DESCRIPCION,TIPO) values ('3','VENDEDOR','EL QUE OPERA','OPERADOR_SECCION');
REM INSERTING into ROL_FUNCION
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_FUNCIONALIDAD
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_FUNCIONALIDAD" ON "FUNCIONALIDAD" ("ID_FUNCIONALIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PERSONA
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_PERSONA" ON "PERSONA" ("ID_PERSONA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ROL
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_ROL" ON "ROL" ("ID_ROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ROL_FUNCION
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_ROL_FUNCION" ON "ROL_FUNCION" ("ID_ROL_FUNCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_PERSONA_DOCUMENTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "UK_PERSONA_DOCUMENTO" ON "PERSONA" ("DOCUMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_ROL_FUNCION
--------------------------------------------------------

  CREATE UNIQUE INDEX "UK_ROL_FUNCION" ON "ROL_FUNCION" ("ID_ROL", "ID_FUNCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_FUNCIONALIDAD
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_FUNCIONALIDAD" ON "FUNCIONALIDAD" ("ID_FUNCIONALIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PERSONA
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_PERSONA" ON "PERSONA" ("ID_PERSONA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_PERSONA_DOCUMENTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "UK_PERSONA_DOCUMENTO" ON "PERSONA" ("DOCUMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ROL
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_ROL" ON "ROL" ("ID_ROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ROL_FUNCION
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_ROL_FUNCION" ON "ROL_FUNCION" ("ID_ROL_FUNCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_ROL_FUNCION
--------------------------------------------------------

  CREATE UNIQUE INDEX "UK_ROL_FUNCION" ON "ROL_FUNCION" ("ID_ROL", "ID_FUNCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table FUNCIONALIDAD
--------------------------------------------------------

  ALTER TABLE "FUNCIONALIDAD" MODIFY ("ID_FUNCIONALIDAD" NOT NULL ENABLE);
  ALTER TABLE "FUNCIONALIDAD" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "FUNCIONALIDAD" ADD CONSTRAINT "PK_FUNCIONALIDAD" PRIMARY KEY ("ID_FUNCIONALIDAD")
  USING INDEX "PK_FUNCIONALIDAD"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PERSONA
--------------------------------------------------------

  ALTER TABLE "PERSONA" MODIFY ("ID_PERSONA" NOT NULL ENABLE);
  ALTER TABLE "PERSONA" MODIFY ("DOCUMENTO" NOT NULL ENABLE);
  ALTER TABLE "PERSONA" MODIFY ("APELLIDO1" NOT NULL ENABLE);
  ALTER TABLE "PERSONA" MODIFY ("APELLIDO2" NOT NULL ENABLE);
  ALTER TABLE "PERSONA" MODIFY ("NOMBRE1" NOT NULL ENABLE);
  ALTER TABLE "PERSONA" MODIFY ("NOMBRE2" NOT NULL ENABLE);
  ALTER TABLE "PERSONA" ADD CONSTRAINT "PK_PERSONA" PRIMARY KEY ("ID_PERSONA")
  USING INDEX "PK_PERSONA"  ENABLE;
  ALTER TABLE "PERSONA" ADD CONSTRAINT "UK_PERSONA_DOCUMENTO" UNIQUE ("DOCUMENTO")
  USING INDEX "UK_PERSONA_DOCUMENTO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROL
--------------------------------------------------------

  ALTER TABLE "ROL" MODIFY ("ID_ROL" NOT NULL ENABLE);
  ALTER TABLE "ROL" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ROL" ADD CONSTRAINT "PK_ROL" PRIMARY KEY ("ID_ROL")
  USING INDEX "PK_ROL"  ENABLE;
  ALTER TABLE "ROL" MODIFY ("TIPO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROL_FUNCION
--------------------------------------------------------

  ALTER TABLE "ROL_FUNCION" MODIFY ("ID_ROL_FUNCION" NOT NULL ENABLE);
  ALTER TABLE "ROL_FUNCION" MODIFY ("ID_ROL" NOT NULL ENABLE);
  ALTER TABLE "ROL_FUNCION" ADD CONSTRAINT "PK_ROL_FUNCION" PRIMARY KEY ("ID_ROL_FUNCION")
  USING INDEX "PK_ROL_FUNCION"  ENABLE;
  ALTER TABLE "ROL_FUNCION" ADD CONSTRAINT "UK_ROL_FUNCION" UNIQUE ("ID_ROL", "ID_FUNCION")
  USING INDEX "UK_ROL_FUNCION"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ROL_FUNCION
--------------------------------------------------------

  ALTER TABLE "ROL_FUNCION" ADD CONSTRAINT "FK_ROL" FOREIGN KEY ("ID_ROL")
	  REFERENCES "ROL" ("ID_ROL") ENABLE;
  ALTER TABLE "ROL_FUNCION" ADD CONSTRAINT "FK_FUNCION" FOREIGN KEY ("ID_FUNCION")
	  REFERENCES "FUNCIONALIDAD" ("ID_FUNCIONALIDAD") ENABLE;
